### ISSUE TITLE
Decide on a name for the organization

### ISSUE THREAD

**Issue by asg017** [asg017/os-club-constitution#1]
[Student Life](https://students.ucsd.edu/_files/student-life/involvement/organizations/studentorgconstitutiontemplate_updated-8.20.18.docx) says that the name can't be something like "UCSD Bowling Club", and instead should be like "Bowling  @ UCSD". Only matter if we want "UCSD" to be in the name, however

This will complete Article 1 and Article 3 of the constitution.

**Comment by bghoang** [comment]
Proposal: "Triton Open Source" or "Triton Source"???

**Comment by KaustubhLall** [comment]
Open Trition
ForkSD
University of Contributions, San Diego

**Comment by KaustubhLall** [comment]
ForkSD
