### ISSUE TITLE
[META] How do we "vote" on PR's that get merged into this constitution?

### ISSUE THREAD

**Issue by asg017** [asg017/os-club-constitution#12]
How do we decide what goes in the constitution and what doesnt? Who decides what PRs get merged in and what doesnt? 

[I'm talking about constitutional changes thatll happen in the next few weeks, not for voting on board members later down the road. Once the constitution is fully written and approved, this wont be an issue anymore).

**Comment by asg017** [comment]
My Thoughts:

1. Majority rules. We create a list of people who can vote on issues, then they can 👍 or 👎 the PRs on GitHub to vote.

One problem: How do we decide who's on this list? Should anyone be able to join? (I think yes, maybe if you fork this repo + add your name to a new `members.md` file or something, then you're "in")

2. "General consensus". As long as there's no big pushback, we go for it. 

3. Combination of 1 and 2. Probably would need Majority rules for big things like the name, but can also do "general consensus" for smaller things.

**Comment by bghoang** [comment]
I think fork the repo and add your name to a file are not really enough since for example I can just do that and decide to not participate in any other events. In that case, I do not think it is a good idea to let me vote.

**Comment by asg017** [comment]
Wait, I dont think I explained this well - This is for us voting on what should/shouldnt go into the constitution right now, not for club members voting for executive board members later. This wont be a problem anymore after we determine what goes into the constitution. I'll update the description to reflect this, my bad!

**Comment by asg017** [comment]
We decided that we would 👍 or 👎 on proposal PR's, and as long as there were 6-7 👍 and less than 3 👎 , we'd assume general consensus and merge it in.
