### ISSUE TITLE
Create a Code of Conduct for Members + board

### ISSUE THREAD

**Issue by asg017** [asg017/os-club-constitution#20]
Idea came up in #18 - We want anyone to be a member, but what if a member is actively making our community exclusive, or is problematic for other reasons?

Should we have a Code of Conduct that all members must follow? What happens if a member doesn't follow it? Should there be a separate CoC for board members?

**Comment by asg017** [comment]
For this, we need:

- [ ] A Code of Conduct 
- [ ] Add a note to the "Membership" section of constitution about the CoC
- [ ] Add a note in constitution about what happens when a member breaks the CoC
- [ ] Add a note in constitution about what happens when a **board member** breaks the CoC
- [ ] Maybe a note about which board member is responsible for changing/updating the CoC?

There are many Code of Conduct examples out there for Open Source - like the [Contributor Covenant](https://www.contributor-covenant.org/). It would also be nice to add [UC San Diego Principles of Community](https://ucsd.edu/about/principles.html) inside our CoC as well - similar to what [ECE USC has](https://github.com/eceusc/code-of-conduct).

**Comment by chrisjrobles** [comment]
I got this

**Comment by asg017** [comment]
Closed with #23!
