### ISSUE TITLE
Board Member Logistics - elections, eligibility, replacement/removal

### ISSUE THREAD

**Issue by asg017** [asg017/os-club-constitution#21]
Seems like we have a pretty good idea of the officers + titles, but now, we have these questions to answer:

- [x] How are officers elected? 
- [x] When are they elected (month), and for what period? 
- [x] Who is eligible for office? 
- [x] When do officers assume their positions? 
- [x] How are officers replaced/removed?

**Comment by asg017** [comment]
@KaustubhLall  will do election related stuff
@julian1999 will do removal stuff

**Comment by julian1999** [comment]
I'll be working on how officers are replaced/removed

**Comment by KaustubhLall** [comment]
Should I leave a draft here?

**Comment by asg017** [comment]
You can just make the pull request, use that as a draft! We can comment on that if something comes up. Do mention this issue in that PR, though, like "this OR is related to #21" or something

**Comment by asg017** [comment]
Closing this, since we've sent in a few PRs for all these!
